/******************************************************************************* 

	AllFile Generated by AllDGenerator

	Authors:		ArcLib team, see AUTHORS file
	Maintainer:		Clay Smith (clayasaurus at gmail dot com)
	License:		zlib/libpng license: $(LICENSE) 
	Copyright:		ArcLib team 

	Description:    
		AllFile Module imports all files below subdirectory

*******************************************************************************/

module arc.all;

public import
	arc.draw.all,
	arc.math.all,
	arc.memory.all,
	arc.templates.all,
	arc.text.all,
	arc.input,
	arc.texture,
	arc.time,
	arc.types,
	arc.window,
	arc.font,
	arc.sound,
	arc.game;
